---

- name: Install NodeJS Dependencies
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - build-essential
    - openssl
    - libssl-dev
    - curl

- name: Install NVM
  sudo: no
  shell: "curl https://raw.githubusercontent.com/creationix/nvm/v0.23.1/install.sh | bash"
  args:
    creates: ~/.nvm

- name: Install npm
  sudo: no
  shell: "source ~/.nvm/nvm.sh && nvm install 0.10.35 && nvm alias default stable"
  args:
    executable: /bin/bash

- name: Get npm bin location
  sudo: no
  shell: "source ~/.nvm/nvm.sh && which npm"
  register: npm_bin
  args:
    executable: /bin/bash

- name: Install npm packages
  sudo: no
  shell: "{{ npm_bin.stdout }} -g install {{ item }}"
  with_items: npm_packages
  args:
    executable: /bin/bash
