---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/web
    ruby_version: 2.2.0
    ruby_gems:
      - sass
      - compass
    npm_packages:
      - yo
      - grunt
      - bower
      - gulp
  roles:
    - init
    - apache
    - nodejs
    - postgres
    - rvm
